import { UploadWorkbench } from "@/components/upload-workbench";
import type { QuantityRow } from "@/lib/types";

const sampleRows: QuantityRow[] = [
  {
    floor: "一层",
    spaceName: "一层-客厅",
    spaceType: "客厅",
    floorAreaM2: 30,
    ceilingAreaM2: 30,
    wallMeasureLengthM: 15,
    heightM: 2.8,
    windowWidthTotalM: 3.2,
    windowsillLengthM: 3.2,
    curtainWallWidthM: 6,
    curtainWallWidthSource: "fallback_longest_wall",
    windowAreaM2: 4.8,
    doorWidthTotalM: 0.9,
    doorDeductAreaM2: 0,
    wallGrossAreaM2: 42,
    latexPaintAreaM2: 39.72,
    wallTileMeasureLengthM: 0,
    wallTileAreaM2: 0,
    floorTilePieceCount: 28,
    electricalScopeAreaM2: 30,
    plumbingScopeAreaM2: 30,
    newWallLengthM: 0,
    newWallAreaM2: 0,
    demolitionWallLengthM: 0,
    demolitionWallAreaM2: 0,
    interiorDoorCount: 1,
    bathroomDoorCount: 0,
    slidingDoorAreaM2: 0,
    slidingDoorCasingLengthM: 0,
    kitchenBaseCabinetLengthM: 0,
    kitchenWallCabinetLengthM: 0,
    customCabinetAreaM2: 0,
    toiletCount: 0,
    bathroomVanityCount: 0,
    waterproofAreaM2: 0,
    evidence: "墙面乳胶漆基数 15m + 门洞 0.9m = 44.52m2；墙面乳胶漆面积 44.52m2 - 窗洞 4.8m2 - 已选门洞扣减 0m2 = 39.72m2。",
    anomalies: [],
    status: "pending_review",
  },
  {
    floor: "一层",
    spaceName: "一层-卫生间",
    spaceType: "卫生间",
    floorAreaM2: 5.28,
    ceilingAreaM2: 5.28,
    wallMeasureLengthM: 9.2,
    heightM: 2.8,
    windowWidthTotalM: 0.8,
    windowsillLengthM: 0.8,
    curtainWallWidthM: 0,
    curtainWallWidthSource: "not_applicable",
    windowAreaM2: 0.64,
    doorWidthTotalM: 0.8,
    doorDeductAreaM2: 0,
    wallGrossAreaM2: 25.76,
    latexPaintAreaM2: 27.36,
    wallTileMeasureLengthM: 9.2,
    wallTileAreaM2: 20.68,
    floorTilePieceCount: 5,
    electricalScopeAreaM2: 5.28,
    plumbingScopeAreaM2: 5.28,
    newWallLengthM: 0,
    newWallAreaM2: 0,
    demolitionWallLengthM: 0,
    demolitionWallAreaM2: 0,
    interiorDoorCount: 1,
    bathroomDoorCount: 1,
    slidingDoorAreaM2: 0,
    slidingDoorCasingLengthM: 0,
    kitchenBaseCabinetLengthM: 0,
    kitchenWallCabinetLengthM: 0,
    customCabinetAreaM2: 0,
    toiletCount: 1,
    bathroomVanityCount: 1,
    waterproofAreaM2: 21.84,
    evidence: "墙面乳胶漆基数 9.2m + 门洞 0.8m = 28m2；墙面乳胶漆面积 28m2 - 窗洞 0.64m2 - 已选门洞扣减 0m2 = 27.36m2。",
    anomalies: [],
    status: "pending_review",
  },
  {
    floor: "一层",
    spaceName: "一层-电梯井",
    spaceType: "其他",
    floorAreaM2: 3.24,
    ceilingAreaM2: 3.24,
    wallMeasureLengthM: 0,
    heightM: 2.8,
    windowWidthTotalM: 0,
    windowsillLengthM: 0,
    curtainWallWidthM: 0,
    curtainWallWidthSource: "not_applicable",
    windowAreaM2: 0,
    doorWidthTotalM: 0,
    doorDeductAreaM2: 0,
    wallGrossAreaM2: 0,
    latexPaintAreaM2: 0,
    wallTileMeasureLengthM: 0,
    wallTileAreaM2: 0,
    floorTilePieceCount: 4,
    electricalScopeAreaM2: 3.24,
    plumbingScopeAreaM2: 3.24,
    newWallLengthM: 0,
    newWallAreaM2: 0,
    demolitionWallLengthM: 0,
    demolitionWallAreaM2: 0,
    interiorDoorCount: 0,
    bathroomDoorCount: 0,
    slidingDoorAreaM2: 0,
    slidingDoorCasingLengthM: 0,
    kitchenBaseCabinetLengthM: 0,
    kitchenWallCabinetLengthM: 0,
    customCabinetAreaM2: 0,
    toiletCount: 0,
    bathroomVanityCount: 0,
    waterproofAreaM2: 0,
    evidence: "电梯井默认识别但不计价。",
    anomalies: [],
    status: "excluded",
  },
];

export default function Home() {
  return <UploadWorkbench initialRows={sampleRows} />;
}
