import { UploadWorkbench } from "@/components/upload-workbench";
import type { QuantityRow } from "@/lib/types";

const sampleRows: QuantityRow[] = [
  {
    floor: "一层",
    spaceName: "一层-客厅",
    spaceType: "客厅",
    floorAreaM2: 30,
    ceilingAreaM2: 30,
    wallMeasureLengthM: 15,
    heightM: 2.8,
    windowWidthTotalM: 3.2,
    windowsillLengthM: 3.2,
    curtainWallWidthM: 6,
    curtainWallWidthSource: "fallback_longest_wall",
    windowAreaM2: 4.8,
    doorWidthTotalM: 0.9,
    doorDeductAreaM2: 0,
    wallGrossAreaM2: 42,
    latexPaintAreaM2: 37.2,
    wallTileMeasureLengthM: 0,
    wallTileAreaM2: 0,
    newWallLengthM: 0,
    newWallAreaM2: 0,
    demolitionWallLengthM: 0,
    demolitionWallAreaM2: 0,
    waterproofAreaM2: 0,
    evidence: "15m * 2.8m - 窗洞 4.8m2；普通房门门洞默认不扣减。",
    anomalies: [],
    status: "pending_review",
  },
  {
    floor: "一层",
    spaceName: "一层-卫生间",
    spaceType: "卫生间",
    floorAreaM2: 5.28,
    ceilingAreaM2: 5.28,
    wallMeasureLengthM: 9.2,
    heightM: 2.8,
    windowWidthTotalM: 0.8,
    windowsillLengthM: 0.8,
    curtainWallWidthM: 0,
    curtainWallWidthSource: "not_applicable",
    windowAreaM2: 0.64,
    doorWidthTotalM: 0.8,
    doorDeductAreaM2: 0,
    wallGrossAreaM2: 25.76,
    latexPaintAreaM2: 25.12,
    wallTileMeasureLengthM: 9.2,
    wallTileAreaM2: 20.68,
    newWallLengthM: 0,
    newWallAreaM2: 0,
    demolitionWallLengthM: 0,
    demolitionWallAreaM2: 0,
    waterproofAreaM2: 21.84,
    evidence: "9.2m * 2.8m - 窗洞 0.64m2；普通房门门洞默认不扣减。",
    anomalies: [],
    status: "pending_review",
  },
  {
    floor: "一层",
    spaceName: "一层-电梯井",
    spaceType: "其他",
    floorAreaM2: 3.24,
    ceilingAreaM2: 3.24,
    wallMeasureLengthM: 0,
    heightM: 2.8,
    windowWidthTotalM: 0,
    windowsillLengthM: 0,
    curtainWallWidthM: 0,
    curtainWallWidthSource: "not_applicable",
    windowAreaM2: 0,
    doorWidthTotalM: 0,
    doorDeductAreaM2: 0,
    wallGrossAreaM2: 0,
    latexPaintAreaM2: 0,
    wallTileMeasureLengthM: 0,
    wallTileAreaM2: 0,
    newWallLengthM: 0,
    newWallAreaM2: 0,
    demolitionWallLengthM: 0,
    demolitionWallAreaM2: 0,
    waterproofAreaM2: 0,
    evidence: "电梯井默认识别但不计价。",
    anomalies: [],
    status: "excluded",
  },
];

export default function Home() {
  return <UploadWorkbench initialRows={sampleRows} />;
}
