import assert from "node:assert/strict";
import { calibrationTemplateFileName, quantityRowsToCalibrationTemplate } from "./calibration-template.ts";
import type { QuantityRow } from "./types.ts";

const rows: QuantityRow[] = [
  {
    floor: "一层",
    spaceName: "厨房",
    spaceType: "厨房",
    floorAreaM2: 4.48,
    ceilingAreaM2: 4.48,
    wallMeasureLengthM: 9.12,
    heightM: 2.8,
    windowWidthTotalM: 0,
    windowsillLengthM: 0,
    curtainWallWidthM: 0,
    curtainWallWidthSource: "manual_required_l_shape_window",
    windowAreaM2: 0,
    doorWidthTotalM: 1,
    doorDeductAreaM2: 0,
    wallGrossAreaM2: 25.54,
    latexPaintAreaM2: 25.54,
    wallTileMeasureLengthM: 9.12,
    wallTileAreaM2: 20.7,
    floorTilePieceCount: 5,
    electricalScopeAreaM2: 4.48,
    plumbingScopeAreaM2: 4.48,
    customCabinetAreaM2: 7.2,
    customCabinetLengthM: 2,
    newWallLengthM: 0,
    newWallAreaM2: 0,
    demolitionWallLengthM: 0,
    demolitionWallAreaM2: 0,
    interiorDoorCount: 0,
    kitchenBaseCabinetLengthM: 4.3,
    kitchenWallCabinetLengthM: 3,
    toiletCount: 1,
    bathroomVanityCount: 1,
    waterproofAreaM2: 7.22,
    evidence: "not exported",
    anomalies: [],
    status: "pending_review",
  },
];

assert.deepEqual(quantityRowsToCalibrationTemplate(rows), [
  {
    space_name: "厨房",
    space_type: "厨房",
    floor_area_m2: 4.48,
    wall_measure_length_m: 9.12,
    window_width_total_m: 0,
    windowsill_length_m: 0,
    curtain_wall_width_m: 0,
    curtain_wall_width_source: "manual_required_l_shape_window",
    window_area_m2: 0,
    door_width_total_m: 1,
    door_deduct_area_m2: 0,
    wall_gross_area_m2: 25.54,
    latex_paint_area_m2: 25.54,
    wall_tile_measure_length_m: 9.12,
    wall_tile_area_m2: 20.7,
    floor_tile_piece_count: 5,
    electrical_scope_area_m2: 4.48,
    plumbing_scope_area_m2: 4.48,
    custom_cabinet_area_m2: 7.2,
    custom_cabinet_length_m: 2,
    new_wall_length_m: 0,
    new_wall_area_m2: 0,
    demolition_wall_length_m: 0,
    demolition_wall_area_m2: 0,
    interior_door_count: 0,
    kitchen_base_cabinet_length_m: 4.3,
    kitchen_wall_cabinet_length_m: 3,
    toilet_count: 1,
    bathroom_vanity_count: 1,
    status: "pending_review",
    anomalies: [],
  },
]);

assert.equal(calibrationTemplateFileName("test-case.dxf"), "test-case.calibration.json");
assert.equal(calibrationTemplateFileName("样例数据"), "calibration-template.json");
