import type { QuantityRow, QuantitySummary } from "./types";

export const DEFAULT_PROJECT_FILE_NAME = "10.dxf";

export const defaultProjectSummary: QuantitySummary = {
  space_count: 8,
  building_area_m2: 136.24,
  floor_area_total_m2: 116.62,
  wall_measure_length_total_m: 102.93,
  window_area_total_m2: 38.26,
  latex_paint_area_total_m2: 207.04,
};

export const defaultProjectRows: QuantityRow[] = [
  {
    floor: "一层",
    spaceName: "餐厅",
    spaceType: "餐厅",
    floorAreaM2: 13.13,
    ceilingAreaM2: 13.13,
    wallMeasureLengthM: 10.06,
    heightM: 2.8,
    windowWidthTotalM: 4.19,
    windowsillLengthM: 4.19,
    curtainWallWidthM: 4.19,
    curtainWallWidthSource: "matched_l_shape_window",
    windowAreaM2: 7.54,
    doorWidthTotalM: 1.75,
    doorDeductAreaM2: 3.68,
    wallGrossAreaM2: 28.17,
    latexPaintAreaM2: 21.85,
    wallTileMeasureLengthM: 0,
    wallTileAreaM2: 0,
    floorTilePieceCount: 13,
    electricalScopeAreaM2: 13.13,
    plumbingScopeAreaM2: 13.13,
    newWallLengthM: 0,
    newWallAreaM2: 0,
    demolitionWallLengthM: 0,
    demolitionWallAreaM2: 0,
    interiorDoorCount: 0,
    bathroomDoorCount: 0,
    slidingDoorAreaM2: 0,
    slidingDoorCasingLengthM: 0,
    kitchenBaseCabinetLengthM: 0,
    kitchenWallCabinetLengthM: 0,
    customCabinetAreaM2: 11.13,
    toiletCount: 0,
    bathroomVanityCount: 0,
    waterproofAreaM2: 0,
    evidence: "墙面展开面积 10.06m * 2.8m = 28.17m2；墙面乳胶漆基数 10.06m + 门洞 1.75m = 33.07m2；墙面乳胶漆面积 33.07m2 - 窗洞 7.54m2 - 已选门洞扣减 3.68m2 - 贴砖墙面 0m2 = 21.85m2。",
    anomalies: [],
    status: "pending_review",
  },
  {
    floor: "一层",
    spaceName: "厨房",
    spaceType: "厨房",
    floorAreaM2: 4.96,
    ceilingAreaM2: 4.96,
    ceilingFinishType: "integrated",
    wallMeasureLengthM: 7.53,
    heightM: 2.8,
    windowWidthTotalM: 1.28,
    windowsillLengthM: 1.28,
    curtainWallWidthM: 0,
    curtainWallWidthSource: "not_applicable",
    windowAreaM2: 2.3,
    doorWidthTotalM: 1.75,
    doorDeductAreaM2: 3.68,
    wallGrossAreaM2: 21.08,
    latexPaintAreaM2: 0,
    wallTileMeasureLengthM: 7.53,
    wallTileAreaM2: 12.84,
    floorTilePieceCount: 5,
    electricalScopeAreaM2: 4.96,
    plumbingScopeAreaM2: 4.96,
    newWallLengthM: 0,
    newWallAreaM2: 0,
    demolitionWallLengthM: 0,
    demolitionWallAreaM2: 0,
    interiorDoorCount: 0,
    bathroomDoorCount: 0,
    slidingDoorAreaM2: 3.68,
    slidingDoorCasingLengthM: 5.95,
    kitchenBaseCabinetLengthM: 5.11,
    kitchenWallCabinetLengthM: 4.33,
    customCabinetAreaM2: 0,
    toiletCount: 0,
    bathroomVanityCount: 0,
    waterproofAreaM2: 7.22,
    evidence: "墙面展开面积 7.53m * 2.8m = 21.08m2；墙面乳胶漆基数 7.53m + 门洞 1.75m = 25.98m2；厨房/卫生间墙面默认贴砖 12.84m2，墙面乳胶漆面积计 0m2。",
    anomalies: [],
    status: "pending_review",
  },
  {
    floor: "一层",
    spaceName: "卫生间",
    spaceType: "卫生间",
    floorAreaM2: 2.92,
    ceilingAreaM2: 2.92,
    ceilingFinishType: "integrated",
    wallMeasureLengthM: 6.06,
    heightM: 2.8,
    windowWidthTotalM: 0.92,
    windowsillLengthM: 0.92,
    curtainWallWidthM: 0,
    curtainWallWidthSource: "not_applicable",
    windowAreaM2: 1.66,
    doorWidthTotalM: 0.8,
    doorDeductAreaM2: 0,
    wallGrossAreaM2: 16.97,
    latexPaintAreaM2: 0,
    wallTileMeasureLengthM: 6.06,
    wallTileAreaM2: 11.81,
    floorTilePieceCount: 3,
    electricalScopeAreaM2: 2.92,
    plumbingScopeAreaM2: 2.92,
    newWallLengthM: 0,
    newWallAreaM2: 0,
    demolitionWallLengthM: 0,
    demolitionWallAreaM2: 0,
    interiorDoorCount: 0,
    bathroomDoorCount: 1,
    slidingDoorAreaM2: 0,
    slidingDoorCasingLengthM: 0,
    kitchenBaseCabinetLengthM: 0,
    kitchenWallCabinetLengthM: 0,
    customCabinetAreaM2: 0,
    toiletCount: 1,
    bathroomVanityCount: 1,
    waterproofAreaM2: 13.83,
    evidence: "墙面展开面积 6.06m * 2.8m = 16.97m2；墙面乳胶漆基数 6.06m + 门洞 0.8m = 19.21m2；厨房/卫生间墙面默认贴砖 11.81m2，墙面乳胶漆面积计 0m2。",
    anomalies: [],
    status: "pending_review",
  },
  {
    floor: "一层",
    spaceName: "卫生间",
    spaceType: "卫生间",
    floorAreaM2: 3.38,
    ceilingAreaM2: 3.38,
    ceilingFinishType: "integrated",
    wallMeasureLengthM: 6.58,
    heightM: 2.8,
    windowWidthTotalM: 1.02,
    windowsillLengthM: 1.02,
    curtainWallWidthM: 0,
    curtainWallWidthSource: "not_applicable",
    windowAreaM2: 1.84,
    doorWidthTotalM: 0.8,
    doorDeductAreaM2: 0,
    wallGrossAreaM2: 18.42,
    latexPaintAreaM2: 0,
    wallTileMeasureLengthM: 6.58,
    wallTileAreaM2: 12.93,
    floorTilePieceCount: 4,
    electricalScopeAreaM2: 3.38,
    plumbingScopeAreaM2: 3.38,
    newWallLengthM: 0,
    newWallAreaM2: 0,
    demolitionWallLengthM: 0,
    demolitionWallAreaM2: 0,
    interiorDoorCount: 0,
    bathroomDoorCount: 1,
    slidingDoorAreaM2: 0,
    slidingDoorCasingLengthM: 0,
    kitchenBaseCabinetLengthM: 0,
    kitchenWallCabinetLengthM: 0,
    customCabinetAreaM2: 0,
    toiletCount: 1,
    bathroomVanityCount: 1,
    waterproofAreaM2: 15.22,
    evidence: "墙面展开面积 6.58m * 2.8m = 18.42m2；墙面乳胶漆基数 6.58m + 门洞 0.8m = 20.66m2；厨房/卫生间墙面默认贴砖 12.93m2，墙面乳胶漆面积计 0m2。",
    anomalies: [],
    status: "pending_review",
  },
  {
    floor: "一层",
    spaceName: "卧室",
    spaceType: "卧室",
    floorAreaM2: 9.85,
    ceilingAreaM2: 9.85,
    wallMeasureLengthM: 12.3,
    heightM: 2.8,
    windowWidthTotalM: 1.77,
    windowsillLengthM: 1.77,
    curtainWallWidthM: 1.77,
    curtainWallWidthSource: "matched_window_wall",
    windowAreaM2: 3.19,
    doorWidthTotalM: 0.9,
    doorDeductAreaM2: 0,
    wallGrossAreaM2: 34.44,
    latexPaintAreaM2: 33.77,
    wallTileMeasureLengthM: 0,
    wallTileAreaM2: 0,
    floorTilePieceCount: 10,
    electricalScopeAreaM2: 9.85,
    plumbingScopeAreaM2: 9.85,
    newWallLengthM: 0,
    newWallAreaM2: 0,
    demolitionWallLengthM: 0,
    demolitionWallAreaM2: 0,
    interiorDoorCount: 1,
    bathroomDoorCount: 0,
    slidingDoorAreaM2: 0,
    slidingDoorCasingLengthM: 0,
    kitchenBaseCabinetLengthM: 0,
    kitchenWallCabinetLengthM: 0,
    customCabinetAreaM2: 4.63,
    toiletCount: 0,
    bathroomVanityCount: 0,
    waterproofAreaM2: 0,
    evidence: "墙面展开面积 12.3m * 2.8m = 34.44m2；墙面乳胶漆基数 12.3m + 门洞 0.9m = 36.96m2；墙面乳胶漆面积 36.96m2 - 窗洞 3.19m2 - 已选门洞扣减 0m2 - 贴砖墙面 0m2 = 33.77m2。",
    anomalies: [],
    status: "pending_review",
  },
  {
    floor: "一层",
    spaceName: "主卧",
    spaceType: "卧室",
    floorAreaM2: 19.21,
    ceilingAreaM2: 19.21,
    wallMeasureLengthM: 16.81,
    heightM: 2.8,
    windowWidthTotalM: 3.47,
    windowsillLengthM: 3.47,
    curtainWallWidthM: 3.47,
    curtainWallWidthSource: "matched_l_shape_window",
    windowAreaM2: 6.25,
    doorWidthTotalM: 1.7,
    doorDeductAreaM2: 0,
    wallGrossAreaM2: 47.07,
    latexPaintAreaM2: 45.58,
    wallTileMeasureLengthM: 0,
    wallTileAreaM2: 0,
    floorTilePieceCount: 18,
    electricalScopeAreaM2: 19.21,
    plumbingScopeAreaM2: 19.21,
    newWallLengthM: 0,
    newWallAreaM2: 0,
    demolitionWallLengthM: 0,
    demolitionWallAreaM2: 0,
    interiorDoorCount: 1,
    bathroomDoorCount: 0,
    slidingDoorAreaM2: 0,
    slidingDoorCasingLengthM: 0,
    kitchenBaseCabinetLengthM: 0,
    kitchenWallCabinetLengthM: 0,
    customCabinetAreaM2: 11.44,
    toiletCount: 0,
    bathroomVanityCount: 0,
    waterproofAreaM2: 0,
    evidence: "墙面展开面积 16.81m * 2.8m = 47.07m2；墙面乳胶漆基数 16.81m + 门洞 1.7m = 51.83m2；墙面乳胶漆面积 51.83m2 - 窗洞 6.25m2 - 已选门洞扣减 0m2 - 贴砖墙面 0m2 = 45.58m2。",
    anomalies: [],
    status: "pending_review",
  },
  {
    floor: "一层",
    spaceName: "卧室",
    spaceType: "卧室",
    floorAreaM2: 11.9,
    ceilingAreaM2: 11.9,
    wallMeasureLengthM: 13.55,
    heightM: 2.8,
    windowWidthTotalM: 1.97,
    windowsillLengthM: 1.97,
    curtainWallWidthM: 1.97,
    curtainWallWidthSource: "matched_window_wall",
    windowAreaM2: 3.55,
    doorWidthTotalM: 0.9,
    doorDeductAreaM2: 0,
    wallGrossAreaM2: 37.94,
    latexPaintAreaM2: 36.91,
    wallTileMeasureLengthM: 0,
    wallTileAreaM2: 0,
    floorTilePieceCount: 12,
    electricalScopeAreaM2: 11.9,
    plumbingScopeAreaM2: 11.9,
    newWallLengthM: 0,
    newWallAreaM2: 0,
    demolitionWallLengthM: 0,
    demolitionWallAreaM2: 0,
    interiorDoorCount: 1,
    bathroomDoorCount: 0,
    slidingDoorAreaM2: 0,
    slidingDoorCasingLengthM: 0,
    kitchenBaseCabinetLengthM: 0,
    kitchenWallCabinetLengthM: 0,
    customCabinetAreaM2: 8.48,
    toiletCount: 0,
    bathroomVanityCount: 0,
    waterproofAreaM2: 0,
    evidence: "墙面展开面积 13.55m * 2.8m = 37.94m2；墙面乳胶漆基数 13.55m + 门洞 0.9m = 40.46m2；墙面乳胶漆面积 40.46m2 - 窗洞 3.55m2 - 已选门洞扣减 0m2 - 贴砖墙面 0m2 = 36.91m2。",
    anomalies: [],
    status: "pending_review",
  },
  {
    floor: "一层",
    spaceName: "客厅",
    spaceType: "客厅",
    floorAreaM2: 51.27,
    ceilingAreaM2: 51.27,
    wallMeasureLengthM: 30.04,
    heightM: 2.8,
    windowWidthTotalM: 6.63,
    windowsillLengthM: 6.63,
    curtainWallWidthM: 6.63,
    curtainWallWidthSource: "matched_window_wall",
    windowAreaM2: 11.93,
    doorWidthTotalM: 4.7,
    doorDeductAreaM2: 0,
    wallGrossAreaM2: 84.11,
    latexPaintAreaM2: 68.93,
    wallTileMeasureLengthM: 5.86,
    wallTileAreaM2: 16.41,
    floorTilePieceCount: 48,
    electricalScopeAreaM2: 51.27,
    plumbingScopeAreaM2: 51.27,
    newWallLengthM: 4,
    newWallAreaM2: 11.2,
    demolitionWallLengthM: 0,
    demolitionWallAreaM2: 0,
    interiorDoorCount: 0,
    bathroomDoorCount: 0,
    slidingDoorAreaM2: 0,
    slidingDoorCasingLengthM: 0,
    kitchenBaseCabinetLengthM: 0,
    kitchenWallCabinetLengthM: 0,
    customCabinetAreaM2: 28.26,
    toiletCount: 0,
    bathroomVanityCount: 0,
    waterproofAreaM2: 0,
    evidence: "墙面展开面积 30.04m * 2.8m = 84.11m2；墙面乳胶漆基数 30.04m + 门洞 4.7m = 97.27m2；墙面乳胶漆面积 97.27m2 - 窗洞 11.93m2 - 已选门洞扣减 0m2 - 贴砖墙面 16.41m2 = 68.93m2。",
    anomalies: ["存在疑似大洞口门，请确认是否扣减墙面"],
    status: "pending_review",
  },
];
