import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const uploadWorkbenchSource = readFileSync(new URL("./upload-workbench.tsx", import.meta.url), "utf8");
const hydropowerPanelSource = readFileSync(new URL("./hydropower-review-panel.tsx", import.meta.url), "utf8");
const drawingReviewSource = readFileSync(new URL("./drawing-review.tsx", import.meta.url), "utf8");
const hydropowerReviewPanelSource = readFileSync(new URL("./hydropower-review-panel.tsx", import.meta.url), "utf8");

assert.ok(uploadWorkbenchSource.includes("buildQuoteExcelHtml"), "workbench should build Excel draft content from generated quote mapping");
assert.ok(uploadWorkbenchSource.includes("quoteExcelFileName"), "workbench should use the Excel draft filename helper");
assert.ok(uploadWorkbenchSource.includes("下载 Excel 草稿"), "quote mapping panel should expose an Excel draft download button");
assert.ok(uploadWorkbenchSource.includes("预算导出"), "top toolbar should expose a visible budget export button");
assert.ok(uploadWorkbenchSource.includes("空间命名规范"), "top toolbar should expose a designer space naming guide download");
assert.ok(uploadWorkbenchSource.includes("画图规范"), "top toolbar should expose a designer drawing guide download");
assert.ok(uploadWorkbenchSource.includes("handleDownloadSpaceNamingGuide"), "space naming guide should be downloadable from the workbench");
assert.ok(uploadWorkbenchSource.includes("handleDownloadDrawingSpecGuide"), "drawing guide should be downloadable from the workbench");
assert.ok(uploadWorkbenchSource.includes("handleDownloadQuoteExcelDraft"), "Excel draft export should be available before the quote mapping panel is shown");
assert.ok(uploadWorkbenchSource.includes("预算导出："), "top toolbar budget export should show the active budget mode");
assert.ok(uploadWorkbenchSource.includes("方案报价可选项"), "quote mapping panel should explain that optional quote items are included in budget exports");
assert.ok(uploadWorkbenchSource.includes("quoteRuleSearch"), "quote rule panel should keep a search state for fast price edits");
assert.ok(uploadWorkbenchSource.includes("筛选报价规则"), "quote rule panel should expose a visible search control");
assert.ok(uploadWorkbenchSource.includes("显示 {filteredQuoteRules.length}/{quoteRules.length} 项"), "quote rule panel should show filtered rule counts");
assert.ok(uploadWorkbenchSource.includes("groupedQuoteRules.map"), "quote rule table should render grouped filtered rules");
assert.ok(uploadWorkbenchSource.includes("quoteRuleGroups"), "quote rule panel should group rules for faster price editing");
assert.ok(uploadWorkbenchSource.includes("全屋拆改/其他工程"), "quote rule panel should include a construction group");
assert.ok(uploadWorkbenchSource.includes("门窗/定制"), "quote rule panel should include a door and customization group");
assert.ok(uploadWorkbenchSource.includes("quoteRuleGroupTitle"), "quote rule table should render visible group headers");
assert.ok(uploadWorkbenchSource.includes("collapsedQuoteRuleGroups"), "quote rule groups should be collapsible");
assert.ok(uploadWorkbenchSource.includes("handleToggleQuoteRuleGroup"), "quote rule groups should expose a toggle handler");
assert.ok(uploadWorkbenchSource.includes("quoteRuleGroupCount"), "quote rule group headers should show matched rule counts");
assert.ok(uploadWorkbenchSource.includes("没有匹配的报价规则"), "quote rule search should show an empty state");
assert.ok(uploadWorkbenchSource.includes("QUOTE_RULE_GROUPS_STORAGE_KEY"), "quote rule group collapsed state should be stored locally");
assert.ok(uploadWorkbenchSource.includes("const DEFAULT_QUOTE_RULES_STORAGE_VERSION = 9"), "default quote rule storage version should reset stale local edited defaults after price table updates");
assert.ok(uploadWorkbenchSource.includes("handleCollapseAllQuoteRuleGroups"), "quote rule panel should collapse all groups at once");
assert.ok(uploadWorkbenchSource.includes("handleExpandAllQuoteRuleGroups"), "quote rule panel should expand all groups at once");
assert.ok(uploadWorkbenchSource.includes("全部收起"), "quote rule panel should expose collapse all action");
assert.ok(uploadWorkbenchSource.includes("全部展开"), "quote rule panel should expose expand all action");
assert.ok(uploadWorkbenchSource.includes("入户门、推拉门和窗台石仍由方案自动识别"), "manual quote options should explain auto quoted fixed items");
assert.ok(uploadWorkbenchSource.includes("QUOTE_INTEGRATION_STATUS_GROUPS"), "quote panel should define quote integration status groups");
assert.ok(uploadWorkbenchSource.includes("报价接入状态清单"), "quote panel should show the quote integration status summary");
assert.ok(uploadWorkbenchSource.includes("已自动取数"), "quote integration status should include auto-quoted items");
assert.ok(uploadWorkbenchSource.includes("自动取数，需复核"), "quote integration status should include review-needed items");
assert.ok(uploadWorkbenchSource.includes("固定占位/设计师手填"), "quote integration status should include manual placeholder items");
assert.ok(uploadWorkbenchSource.includes("暂不接入"), "quote integration status should include currently excluded items");
assert.ok(uploadWorkbenchSource.includes("manualItems: manualQuoteItemQuantities"), "Excel draft export should apply manual quote item quantities");
assert.ok(uploadWorkbenchSource.includes("manualItemPrices: { [ALUMINUM_WINDOW_ITEM_NAME]: aluminumWindowUnitPrice }"), "Excel draft export should apply manual quote item unit prices");
assert.ok(uploadWorkbenchSource.includes("excelManualItemQuantities: manualQuoteItemQuantities"), "review snapshots should persist manual quote item quantities");
assert.ok(uploadWorkbenchSource.includes("excelManualItemPrices: manualQuoteItemPriceOverrides"), "review snapshots should persist manual quote item price overrides");
assert.ok(uploadWorkbenchSource.includes("manualQuoteInputsFromQuantities(snapshot.excel_manual_item_quantities)"), "review snapshot import should restore manual quote item inputs");
assert.ok(uploadWorkbenchSource.includes("manualQuoteInputsFromPrices(snapshot.excel_manual_item_prices)"), "review snapshot import should restore manual quote item price inputs");
assert.ok(uploadWorkbenchSource.includes("QuoteExcelProjectInfo"), "workbench should type quote project header information");
assert.ok(uploadWorkbenchSource.includes("const [quoteProjectInfo, setQuoteProjectInfo]"), "workbench should keep quote project header state");
assert.ok(uploadWorkbenchSource.includes("方案信息"), "workbench should expose quote project header fields");
assert.ok(uploadWorkbenchSource.includes("确认方案信息"), "workbench should let designers confirm project header fields");
assert.ok(uploadWorkbenchSource.includes("地址名称"), "quote header fields should include address name");
assert.ok(uploadWorkbenchSource.includes("客户姓名"), "quote header fields should include customer name");
assert.ok(uploadWorkbenchSource.includes("设计师"), "quote header fields should include designer name");
assert.ok(uploadWorkbenchSource.includes("报价员"), "quote header fields should include estimator name");
assert.ok(uploadWorkbenchSource.includes("报价日期"), "quote header fields should include quote date");
assert.ok(uploadWorkbenchSource.includes("projectInfo: quoteProjectInfo"), "review snapshots should persist quote project header information");
assert.ok(uploadWorkbenchSource.includes("setQuoteProjectInfo({"), "review snapshot import should restore quote project header information");
assert.ok(uploadWorkbenchSource.includes("decorationAreaM2: summary?.building_area_m2 ?? mapping.summary.building_area_m2"), "Excel draft export should fill decoration area from parsed summary");
assert.ok(uploadWorkbenchSource.includes('buildHydropowerEstimate'), "workbench should build a hydropower estimate from rows and drawing");
assert.ok(uploadWorkbenchSource.includes("HydropowerReviewPanel"), "workbench should render the hydropower review panel");
assert.ok(uploadWorkbenchSource.includes("const [hydropowerOverride, setHydropowerOverride]"), "workbench should keep hydropower override state");
assert.ok(uploadWorkbenchSource.includes("hydropowerSummary: hydropowerEstimate.summary"), "quote mapping export should pass hydropower summary into quote mapping");
assert.ok(uploadWorkbenchSource.includes("hydropower: hydropowerEstimate"), "review snapshot export should persist the current hydropower estimate");
assert.ok(uploadWorkbenchSource.includes("setHydropowerOverride(snapshot.hydropower ?? null)"), "review snapshot import should restore hydropower overrides");
assert.ok(uploadWorkbenchSource.includes("hydropowerPoints={hydropowerEstimate.points}"), "drawing review should receive hydropower point overlays from the workbench");
assert.ok(!uploadWorkbenchSource.includes('{ itemName: "入户门"'), "entry door should be auto quoted instead of shown as a manual Excel option");
assert.ok(uploadWorkbenchSource.includes("bathroomRowsFromRows(rows)"), "manual quote options should use billable bathroom rows");
assert.ok(uploadWorkbenchSource.includes("manualQuoteInputsFromBathroomChoices"), "manual quote options should aggregate per-bathroom choices");
assert.ok(uploadWorkbenchSource.includes("manualBathroomChoices"), "manual quote options should expose per-bathroom choice controls");
assert.ok(uploadWorkbenchSource.includes('const selectedShower = choice.shower ?? "淋浴隔断"'), "bathroom shower choice should default to shower partition in the UI");
assert.ok(uploadWorkbenchSource.includes("application/vnd.ms-excel;charset=utf-8"), "Excel draft download should use an Excel-compatible content type");
assert.ok(hydropowerPanelSource.includes("aggregateHydropowerQuoteSummary"), "hydropower panel should show aggregate quote categories");
assert.ok(hydropowerPanelSource.includes("强电插座"), "hydropower panel should show strong outlet aggregate");
assert.ok(hydropowerPanelSource.includes("设备专线"), "hydropower panel should show equipment circuit aggregate");
assert.ok(hydropowerPanelSource.includes("给水点"), "hydropower panel should show water point aggregate");
assert.ok(hydropowerPanelSource.includes("groupedPoints.map"), "hydropower panel should keep fine-grained per-space sources");
assert.ok(hydropowerPanelSource.includes("hydropowerCategoryGrid"), "hydropower panel should summarize points by space category before details");
assert.ok(hydropowerPanelSource.includes("查看各空间点位明细"), "hydropower panel should keep per-space point details collapsed");
assert.ok(hydropowerPanelSource.includes("确认修改"), "hydropower panel should show a concise confirm-modification action after edits");
assert.ok(!hydropowerPanelSource.includes("系统推算"), "hydropower panel should not use system-internal wording in the designer UI");
assert.ok(drawingReviewSource.includes("hydropowerPoints?: HydropowerPoint[]"), "drawing review should accept hydropower points as an optional overlay prop");
assert.ok(drawingReviewSource.includes("showHydropowerPoints"), "drawing review should expose a hydropower point layer toggle");
assert.ok(drawingReviewSource.includes("svgHydropowerPoint"), "drawing review should render hydropower point markers");
assert.ok(drawingReviewSource.includes("方案完整性复核"), "drawing review should present itself as the designer plan-completeness review area");
assert.ok(drawingReviewSource.includes("检查房间边界、墙线、门窗、吊顶和柜体是否漏画"), "drawing review should explain the designer-facing review purpose");
assert.ok(drawingReviewSource.includes("showMoreDrawingLayers"), "drawing review should hide less frequent layers behind a more-layers control");
assert.ok(drawingReviewSource.includes("const [showBathroomFixtures, setShowBathroomFixtures] = useState(false)"), "drawing review should keep bathroom fixtures hidden by default");
assert.ok(drawingReviewSource.includes("const [showHydropowerPoints, setShowHydropowerPoints] = useState(false)"), "drawing review should keep recommended hydropower points hidden by default");
assert.ok(drawingReviewSource.includes("水电推荐点位"), "drawing review toolbar should label hydropower points as recommendations");
assert.ok(drawingReviewSource.includes("系统推荐点位"), "drawing review point tooltip should explain the overlay markers are recommendations");
assert.ok(drawingReviewSource.includes("showVoids"), "drawing review should expose a void boundary layer toggle");
assert.ok(drawingReviewSource.includes("showGypsumLineCeilings"), "drawing review should expose a gypsum line ceiling layer toggle");
assert.ok(drawingReviewSource.includes("showNoCeilings"), "drawing review should expose a no-ceiling layer toggle");
assert.ok(drawingReviewSource.includes("svgVoidBoundary"), "drawing review should render void boundaries");
assert.ok(drawingReviewSource.includes("svgGypsumLineCeiling"), "drawing review should render gypsum line ceiling boundaries");
assert.ok(drawingReviewSource.includes("svgNoCeiling"), "drawing review should render no-ceiling boundaries");
assert.ok(hydropowerReviewPanelSource.includes("HydropowerEstimate"), "hydropower review panel should type its estimate prop");
assert.ok(hydropowerReviewPanelSource.includes("HydropowerPointKind"), "hydropower review panel should map point kinds to labels");
assert.ok(hydropowerReviewPanelSource.includes("水电点位复核"), "hydropower review panel should render the review heading");
assert.ok(hydropowerReviewPanelSource.includes("确定水电点位"), "hydropower review panel should render the confirm action");
assert.ok(hydropowerReviewPanelSource.includes("onPointQuantityChange"), "hydropower review panel should let the user edit suggested point quantities");
