import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const uploadWorkbenchSource = readFileSync(new URL("./upload-workbench.tsx", import.meta.url), "utf8");
const drawingReviewSource = readFileSync(new URL("./drawing-review.tsx", import.meta.url), "utf8");
const hydropowerReviewPanelSource = readFileSync(new URL("./hydropower-review-panel.tsx", import.meta.url), "utf8");

assert.ok(uploadWorkbenchSource.includes("buildQuoteExcelHtml"), "workbench should build Excel draft content from generated quote mapping");
assert.ok(uploadWorkbenchSource.includes("quoteExcelFileName"), "workbench should use the Excel draft filename helper");
assert.ok(uploadWorkbenchSource.includes("下载 Excel 草稿"), "quote mapping panel should expose an Excel draft download button");
assert.ok(uploadWorkbenchSource.includes("导出 Excel 草稿"), "top toolbar should expose a visible Excel draft export button");
assert.ok(uploadWorkbenchSource.includes("handleDownloadQuoteExcelDraft"), "Excel draft export should be available before the quote mapping panel is shown");
assert.ok(uploadWorkbenchSource.includes("Excel 可选补项"), "quote mapping panel should explain that manual quote items are included in Excel drafts");
assert.ok(uploadWorkbenchSource.includes("quoteRuleSearch"), "quote rule panel should keep a search state for fast price edits");
assert.ok(uploadWorkbenchSource.includes("筛选报价规则"), "quote rule panel should expose a visible search control");
assert.ok(uploadWorkbenchSource.includes("显示 {filteredQuoteRules.length}/{quoteRules.length} 项"), "quote rule panel should show filtered rule counts");
assert.ok(uploadWorkbenchSource.includes("groupedQuoteRules.map"), "quote rule table should render grouped filtered rules");
assert.ok(uploadWorkbenchSource.includes("quoteRuleGroups"), "quote rule panel should group rules for faster price editing");
assert.ok(uploadWorkbenchSource.includes("全屋拆改/其他工程"), "quote rule panel should include a construction group");
assert.ok(uploadWorkbenchSource.includes("门窗/定制"), "quote rule panel should include a door and customization group");
assert.ok(uploadWorkbenchSource.includes("quoteRuleGroupTitle"), "quote rule table should render visible group headers");
assert.ok(uploadWorkbenchSource.includes("collapsedQuoteRuleGroups"), "quote rule groups should be collapsible");
assert.ok(uploadWorkbenchSource.includes("handleToggleQuoteRuleGroup"), "quote rule groups should expose a toggle handler");
assert.ok(uploadWorkbenchSource.includes("quoteRuleGroupCount"), "quote rule group headers should show matched rule counts");
assert.ok(uploadWorkbenchSource.includes("没有匹配的报价规则"), "quote rule search should show an empty state");
assert.ok(uploadWorkbenchSource.includes("QUOTE_RULE_GROUPS_STORAGE_KEY"), "quote rule group collapsed state should be stored locally");
assert.ok(uploadWorkbenchSource.includes("handleCollapseAllQuoteRuleGroups"), "quote rule panel should collapse all groups at once");
assert.ok(uploadWorkbenchSource.includes("handleExpandAllQuoteRuleGroups"), "quote rule panel should expand all groups at once");
assert.ok(uploadWorkbenchSource.includes("全部收起"), "quote rule panel should expose collapse all action");
assert.ok(uploadWorkbenchSource.includes("全部展开"), "quote rule panel should expose expand all action");
assert.ok(uploadWorkbenchSource.includes("自动识别结果处理"), "manual Excel options should explain auto quoted fixed items");
assert.ok(uploadWorkbenchSource.includes("QUOTE_INTEGRATION_STATUS_GROUPS"), "quote panel should define quote integration status groups");
assert.ok(uploadWorkbenchSource.includes("报价接入状态清单"), "quote panel should show the quote integration status summary");
assert.ok(uploadWorkbenchSource.includes("已自动取数"), "quote integration status should include auto-quoted items");
assert.ok(uploadWorkbenchSource.includes("自动取数，需复核"), "quote integration status should include review-needed items");
assert.ok(uploadWorkbenchSource.includes("固定占位/设计师手填"), "quote integration status should include manual placeholder items");
assert.ok(uploadWorkbenchSource.includes("暂不接入"), "quote integration status should include currently excluded items");
assert.ok(uploadWorkbenchSource.includes("manualItems: manualQuoteItemQuantities"), "Excel draft export should apply manual quote item quantities");
assert.ok(uploadWorkbenchSource.includes("excelManualItemQuantities: manualQuoteItemQuantities"), "review snapshots should persist manual quote item quantities");
assert.ok(uploadWorkbenchSource.includes("manualQuoteInputsFromQuantities(snapshot.excel_manual_item_quantities)"), "review snapshot import should restore manual quote item inputs");
assert.ok(uploadWorkbenchSource.includes('buildHydropowerEstimate'), "workbench should build a hydropower estimate from rows and drawing");
assert.ok(uploadWorkbenchSource.includes("HydropowerReviewPanel"), "workbench should render the hydropower review panel");
assert.ok(uploadWorkbenchSource.includes("const [hydropowerOverride, setHydropowerOverride]"), "workbench should keep hydropower override state");
assert.ok(uploadWorkbenchSource.includes("hydropowerSummary: hydropowerEstimate.summary"), "quote mapping export should pass hydropower summary into quote mapping");
assert.ok(uploadWorkbenchSource.includes("hydropower: hydropowerEstimate"), "review snapshot export should persist the current hydropower estimate");
assert.ok(uploadWorkbenchSource.includes("setHydropowerOverride(snapshot.hydropower ?? null)"), "review snapshot import should restore hydropower overrides");
assert.ok(uploadWorkbenchSource.includes("hydropowerPoints={hydropowerEstimate.points}"), "drawing review should receive hydropower point overlays from the workbench");
assert.ok(!uploadWorkbenchSource.includes('{ itemName: "入户门"'), "entry door should be auto quoted instead of shown as a manual Excel option");
assert.ok(uploadWorkbenchSource.includes("bathroomRowsFromRows(rows)"), "manual quote options should use billable bathroom rows");
assert.ok(uploadWorkbenchSource.includes("manualQuoteInputsFromBathroomChoices"), "manual quote options should aggregate per-bathroom choices");
assert.ok(uploadWorkbenchSource.includes("manualBathroomChoices"), "manual quote options should expose per-bathroom choice controls");
assert.ok(uploadWorkbenchSource.includes('const selectedShower = choice.shower ?? "淋浴隔断"'), "bathroom shower choice should default to shower partition in the UI");
assert.ok(uploadWorkbenchSource.includes("application/vnd.ms-excel;charset=utf-8"), "Excel draft download should use an Excel-compatible content type");
assert.ok(drawingReviewSource.includes("hydropowerPoints?: HydropowerPoint[]"), "drawing review should accept hydropower points as an optional overlay prop");
assert.ok(drawingReviewSource.includes("showHydropowerPoints"), "drawing review should expose a hydropower point layer toggle");
assert.ok(drawingReviewSource.includes("svgHydropowerPoint"), "drawing review should render hydropower point markers");
assert.ok(drawingReviewSource.includes("系统估算点位"), "drawing review toolbar should mark the hydropower overlay as system-estimated");
assert.ok(drawingReviewSource.includes("系统推荐点位"), "drawing review point tooltip should explain the overlay markers are recommendations");
assert.ok(hydropowerReviewPanelSource.includes("HydropowerEstimate"), "hydropower review panel should type its estimate prop");
assert.ok(hydropowerReviewPanelSource.includes("HydropowerPointKind"), "hydropower review panel should map point kinds to labels");
assert.ok(hydropowerReviewPanelSource.includes("水电点位复核"), "hydropower review panel should render the review heading");
assert.ok(hydropowerReviewPanelSource.includes("确认水电点位"), "hydropower review panel should render the confirm action");
assert.ok(hydropowerReviewPanelSource.includes("onPointQuantityChange"), "hydropower review panel should let the user edit suggested point quantities");
